### ISSUE TITLE
New Browser-Sync security issue

### ISSUE THREAD

**Issue by genemars** [11ty/eleventy-server-browsersync#2]
Just in case you are not aware of this new issue.

node_modules/portscanner/node_modules/async
  portscanner  0.1.1 - 2.1.1
  Depends on vulnerable versions of async
  node_modules/portscanner
    browser-sync  <=0.6.2 || >=2.0.0-rc1
    Depends on vulnerable versions of portscanner
    node_modules/browser-sync
      @11ty/eleventy-server-browsersync  *
      Depends on vulnerable versions of browser-sync
      node_modules/@11ty/eleventy-server-browsersync

**Comment by zachleat** [comment]
Yeah, this one applies to more than browser-sync (but also browser-sync)

Filed at core too https://github.com/11ty/eleventy/issues/2327

(I’d like to keep this one open too, it seems like the core version might be fixed on a different timeline than the browser-sync one)

**Comment by shakyShane** [comment]
released as browser-sync@2.27.10 - thank you :)

**Comment by zachleat** [comment]
Thank you @shakyShane!
